### ISSUE TITLE
Ошибка при сборке проекта

### ISSUE THREAD

**Issue by akayumeru** [ZigTheHedge/intimepresence#1]
Доброго времени суток, при сборке проекта с добавленным JEI:
build.gradle:
```
repositories {
    maven {
        name = "Progwml6 maven"
        url = "http://dvs1.progwml6.com/files/maven"
    }
    maven {
        name = "ModMaven"
        url = "modmaven.k-4u.nl"
    }
}

dependencies {
    // compile against the JEI API but do not include it at runtime
    deobfProvided "mezz.jei:jei_${mc_version}:${jei_version}:api"
    // at runtime, use the full JEI jar
    runtime "mezz.jei:jei_${mc_version}:${jei_version}"
}
```

Возникает ошибка: `Error:(7, 21) java: package mezz.jei.util does not exist` в `com.cwelth.intimepresence.jei.ITPRecipeCategory`.
`import mezz.jei.util.Translator;`
Хотя сам класс `Translate` существует в пакете. 
![image](https://user-images.githubusercontent.com/25130565/60662882-3e43e300-9e66-11e9-87b5-f569ebcf83de.png)
В чём причина, понять не могу.

**Comment by ZigTheHedge** [comment]
Просто помести бинарник JEI в libs
