### ISSUE TITLE
Duplication bug with 'Carry On' mod

### ISSUE THREAD

**Issue by AKCEJIb** [ZigTheHedge/intimepresence#10]
**Describe the bug**
If we take bottom block of Steam-hammer using 'Carry On' Mod, and place Steam-hammer anywhere else, we can see bounding box of top part this machine at previous place. Right Click on it causing errors in console, but don't crashing. If we destroy this part we get new Steam-hammer.

**To Reproduce**
1. Place Steam-hammer
2. Take bottom part of Steam-hammer
3. Place this Steam-hammer anywhere else
4. Destroy top part of previous Steam-hammer

**Version information**
Forge version: 2838
Mod version: 1.25

**Any additional information**
Screenshot:
https://i.imgur.com/NvbkWNY.jpg

**Comment by ZigTheHedge** [comment]
Should be fixed by now (1.27)
