### ISSUE TITLE
Crash on respawning

### ISSUE THREAD

**Issue by AKCEJIb** [ZigTheHedge/intimepresence#11]
**Describe the bug**
After I died, I appeared at home and the game crashed. This did not happen every time, only 1 time after the dragon killed me (from the mod "Ice and Fire")

**To Reproduce**
I don't know why it's happend, but check crash-log.

**Version information**
Forge version: 2838
Mod version: 1.25

**Crashlog**
https://pastebin.com/Sku82YuN

UPD:
I died from this dragon again and got same crashlog.

**Comment by xmarkers** [comment]
У меня сегодня второй раз выпал майн с похожей проблемой. Как мне кажется, проблема возникает из-за задержек в загрузке чанка ибо как и в топике, у меня вылет тоже происходил после смерти.
Крашлоги:
https://pastebin.com/d9d4ryf3 (Умер от взрыва какого-то моба заспавненого бесконечной пылью (Infinity Dust))
https://pastebin.com/6yrsZKAw (Умер от падения с большой высоты)
Т.е. проблема связана просто с фактом смерти, а не со смертью от какого-то моба из мода.
Может просто вставить костыль, сделать проверку на air? перед обращением к свойствам.
Спасибо!
PS: Судя по крашлогу, исключение возникает тут https://github.com/ZigTheHedge/intimepresence/blob/master/src/main/java/com/cwelth/intimepresence/renderers/SteamHammerTESR.java в 22 строке

**Comment by ZigTheHedge** [comment]
Fixed in 1.28
