### ISSUE TITLE
Паровой молот принимает в качестве топлива - ведро с лавой, но съедает вместе с ведром

### ISSUE THREAD

**Issue by xmarkers** [ZigTheHedge/intimepresence#12]
**Describe the bug**
Если в слот для топлива парового молота, положить ведро лавы, то паровой молот принимает его в качестве топлива и начинает процесс, однако пустое ведро не отдает

**To Reproduce**
Положить ведро с лавой в слот для топлива парового молота

**Version information**
Forge version: 14.23.5.2838
Mod version: 1.27

**Comment by ZigTheHedge** [comment]
Fixed in 1.28
