### ISSUE TITLE
Обработчик осколков потребляет топливо без необходимости

### ISSUE THREAD

**Issue by xmarkers** [ZigTheHedge/intimepresence#13]
Describe the bug
Если заполнить все слоты обработчика осколков для переработки осколков во время, то после того как закончился жемчуг эндера, обработчик осколков продолжает тратить топливо. Возможно стоит сделать "догорание" начатого топлива, но после, остановить его потребление. 

To Reproduce
Положить в обработчик осколков стак угля, один жемчуг эндера, стак пространственных осколков, то после выработки жемчуга эндера, уголь продолжает тратится при этом время не вырабатывается.

Version information
Forge version: 14.23.5.2838
Mod version: 1.27

**Comment by ZigTheHedge** [comment]
Not a bug. And use English please.
