### ISSUE TITLE
[Crash] Ore Generator

### ISSUE THREAD

**Issue by Rumaruka** [ZigTheHedge/intimepresence#15]
Crashlog - https://paste.dimdev.org/xavupeyugu.mccrash
Forge - 14.23.5.2847
Mod Version - 1.28

Don`t setup already create world

**Comment by kellixon** [comment]
Такой же краш (прикрепил полный отчёт) при заходе в майнинг биом из "aroma1997sdimension".
[crash.zip](https://github.com/ZigTheHedge/intimepresence/files/3643357/crash.zip)
ps С версией 1.27 всё отлично.

**Comment by ZigTheHedge** [comment]
Fixed in 1.29
