### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by LotusZadrotus** [ZigTheHedge/intimepresence#5]
Hello!
I got this crash when opened cauldron gui and tried to place  iron ingot and coke coal(added by Immersive Engineering ) by shift+left click.

Forge version:forge 1.12.2-14.23.5.2838
Mod version: 1.16

Crashlog : 

https://pastebin.com/6tAZMBcW

The other side modpack was extended by Immersive Tech and Immersive Petroleum

**Comment by ZigTheHedge** [comment]
Fixed in 1.19. Thanks!
