### ISSUE TITLE
TileEntity updating generate lags

### ISSUE THREAD

**Issue by AKCEJIb** [ZigTheHedge/intimepresence#7]
**Describe the bug**
Like #6 all mod blocks generating strong lags.
Any TileEntity updating start loading all chunks, that player can see. In my case it's 72 chunks.
This causes FPS to drop.

**To Reproduce**
1. Place any block from mod - micro freeze.
2. Place any block near mod block - micro freeze.
3. Activate Time Machine by redstone - fps drop + 72 loaded chunks.
4. Generate time by Shard Processor - fps drop + 72 loaded chunks.
5. Steam-hammer blow - micro freeze.

**Version information**
Forge version: 2838
Mod version: 1.18 - 1.19

**Comment by ZigTheHedge** [comment]
Try 1.195.

**Comment by AKCEJIb** [comment]
> 
> 
> Try 1.195.

UPD: I don't know how it works on other computers, but my settings is:
Graphics: Fancy
Render Distance: 10 chunks
And some other settings is Maximum and Fancy

And my java launch parameters: -mx8G -Xss1024k -XX:MaxMetaspaceSize=1024m -XX:ParallelGCThreads=12 -XX:+UseLargePages -XX:InitiatingHeapOccupancyPercent=10 -XX:AllocatePrefetchStyle=1 -XX:+UseSuperWord -XX:+OptimizeFill -XX:LoopUnrollMin=4 -XX:LoopMaxUnroll=16 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -XX:+CMSCleanOnEnter -XX:+EliminateLocks -XX:+DoEscapeAnalysis -XX:+TieredCompilation -XX:+UseCodeCacheFlushing -XX:+UseFastJNIAccessors -XX:+CMSScavengeBeforeRemark -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+ScavengeBeforeFullGC -XX:+AlwaysPreTouch -XX:+UseFastAccessorMethods -XX:+UnlockExperimentalVMOptions -XX:G1HeapWastePercent=10 -XX:G1MaxNewSizePercent=10 -XX:G1HeapRegionSize=32M -XX:G1NewSizePercent=10 -XX:MaxGCPauseMillis=250 -XX:+OptimizeStringConcat -XX:+UseParNewGC -XX:+UseNUMA -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:SurvivorRatio=2 -XX:+DisableExplicitGC


Better, but you should make more optimization, I recorded video for you.
https://youtu.be/_utZYKkeezo

**Comment by ZigTheHedge** [comment]
Lever FPS drop - try with plain Lever by itself, or connect it to door - the behavior will be the same 
As of putting items in and out - it's standard syncronization with modded tileentities. I can't do anything with it. (Try other mod's machines, containing inventory)
About glitched texture - it doesn't looks like this in dev environment. (Maybe BetterFPS is to be blamed).

**Comment by AKCEJIb** [comment]
> Lever FPS drop - try with plain Lever by itself, or connect it to door - the behavior will be the same

Lever with door don't generate so hard lags, fps drop by ~5-15 only, same with trapdoor and fence gate.
 
> As of putting items in and out - it's standard syncronization with modded tileentities. I can't do anything with it. (Try other mod's machines, containing inventory)

I tested at Tech Reborn Thermal Generator, Iron Furnace, Iron Alloy Smelter and this test don't generate any fps drop, doesn't even fall by ~5-15 FPS.
And I tested Integrated Dynamics Drying Basin, spam RMB with zombie-flash, FPS drop also only by ~5-15.

All test was made in same place in same world. The most important thing that small FPS drop dont generate any freezes, blocks from your mod causes FPS drop when I placed block on ground, FPS drop very small, but causes micro-freeze.

The mod has become more playable, but these problems are absent in other mods, and it seems you are can fix them.

**Comment by syorito-hatsuki** [comment]
Попробую чё будет по FPS на Ryzen 7 2700 + RX560

**Comment by ZigTheHedge** [comment]
Ok. Try 1.2.
I think - that's the best I can do taking into consideration TESR's.

**Comment by AKCEJIb** [comment]
> 
> 
> Ok. Try 1.2.
> I think - that's the best I can do taking into consideration TESR's.

Yes, all lags gone, great job!
