### ISSUE TITLE
Игра вылет при попытки кинуть предметы в SteamHammer при помоши Shift

### ISSUE THREAD

**Issue by syorito-hatsuki** [ZigTheHedge/intimepresence#9]
**Describe the bug** 
Игра вылет с ошибкой 
``` 
The game crashed whilst updating screen events 
Error: java.lang.NullPointerException: Updating screen events 
``` 

**Version information** 
Forge version: 14.23.5.2838
Mod version: 1.18

**Crashlog (if any)** 
https://pastebin.com/8v6hPYF8

**Comment by Rumaruka** [comment]
Обнови мод

**Comment by ZigTheHedge** [comment]
Исправлено в 1.19
